# Generated by Django 3.0.3 on 2020-02-14 21:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_postgres_unlimited_varchar


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blogmark",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("slug", models.SlugField(max_length=64)),
                ("link_url", models.URLField(max_length=1000)),
                ("link_title", models.CharField(max_length=255)),
                ("via_url", models.URLField(blank=True, null=True)),
                ("via_title", models.CharField(blank=True, max_length=255, null=True)),
                ("commentary", models.TextField()),
            ],
            options={"ordering": ("-created",), "abstract": False,},
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("slug", models.SlugField(max_length=64)),
                ("photo", models.ImageField(upload_to="photos/%Y/%M")),
                (
                    "title",
                    django_postgres_unlimited_varchar.UnlimitedCharField(blank=True),
                ),
            ],
            options={"ordering": ("-created",), "abstract": False,},
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("slug", models.SlugField(max_length=64)),
                ("quotation", models.TextField()),
                ("source", models.CharField(max_length=255)),
                (
                    "source_url",
                    django_postgres_unlimited_varchar.UnlimitedCharField(
                        blank=True, null=True
                    ),
                ),
            ],
            options={"ordering": ("-created",), "abstract": False,},
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", django_postgres_unlimited_varchar.UnlimitedCharField()),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
            ],
            options={"verbose_name_plural": "series",},
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("slug", models.SlugField(max_length=64)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                (
                    "tweet_html",
                    models.TextField(
                        blank=True,
                        help_text="Paste in the embed tweet HTML, minus the script tag, \n        to display a tweet in the sidebar next to this entry.",
                        null=True,
                    ),
                ),
                (
                    "extra_head_html",
                    models.TextField(
                        blank=True,
                        help_text="Extra HTML to be included in the &lt;head&gt; for this entry.",
                        null=True,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="blog.Series",
                    ),
                ),
            ],
            options={"ordering": ("-created",), "abstract": False,},
        ),
    ]
